// Reusable CSV/PDF export dropdown for finance & ops pages.
// Optional inline filter sheet (date range, status, client) when filters prop is set.
import { useState, useMemo } from "react";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Popover, PopoverContent, PopoverTrigger } from "@/components/ui/popover";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Download, FileText, FileSpreadsheet, Filter } from "lucide-react";
import { downloadCSV, downloadPDF } from "@/lib/exporters";
import { toast } from "sonner";

export interface ExportFilters {
  /** Field name on each row used for date filtering, e.g. "Created" or "Due Date". */
  dateField?: string;
  /** Field name on each row used for status filtering. */
  statusField?: string;
  /** Available status options (chips) for the dropdown. */
  statusOptions?: string[];
  /** Field name on each row used for client filtering. */
  clientField?: string;
}

interface ExportMenuProps {
  filename: string;
  title: string;
  rows: Record<string, any>[];
  headers?: string[];
  subtitle?: string;
  filters?: ExportFilters;
}

export function ExportMenu({ filename, title, rows, headers, subtitle, filters }: ExportMenuProps) {
  const [from, setFrom] = useState("");
  const [to, setTo] = useState("");
  const [status, setStatus] = useState<string>("all");
  const [client, setClient] = useState("");

  // Apply filters to rows. When no filter set, returns rows untouched.
  const filtered = useMemo(() => {
    if (!filters) return rows;
    return rows.filter((r) => {
      if (filters.dateField && (from || to)) {
        const raw = r[filters.dateField];
        const d = raw ? new Date(String(raw)) : null;
        if (!d || isNaN(d.getTime())) return false;
        if (from && d < new Date(from)) return false;
        if (to && d > new Date(to + "T23:59:59")) return false;
      }
      if (filters.statusField && status !== "all") {
        if (String(r[filters.statusField] ?? "").toLowerCase() !== status.toLowerCase()) return false;
      }
      if (filters.clientField && client.trim()) {
        const v = String(r[filters.clientField] ?? "").toLowerCase();
        if (!v.includes(client.trim().toLowerCase())) return false;
      }
      return true;
    });
  }, [rows, filters, from, to, status, client]);

  const activeFilterCount = [
    from || to,
    status !== "all",
    client.trim(),
  ].filter(Boolean).length;

  const handleCSV = () => {
    try {
      downloadCSV(`${filename}.csv`, filtered, headers);
      toast.success(`CSV exported · ${filtered.length} rows`);
    } catch (e: any) {
      toast.error(e.message || "Export failed");
    }
  };

  const handlePDF = async () => {
    try {
      const sub = subtitle ? `${subtitle}${activeFilterCount ? ` · ${filtered.length} of ${rows.length} rows (filtered)` : ""}` : undefined;
      await downloadPDF(`${filename}.pdf`, title, filtered, headers, { subtitle: sub, footer: "Generated by Digital Penta · digitalpenta.com" });
      toast.success(`PDF exported · ${filtered.length} rows`);
    } catch (e: any) {
      toast.error(e.message || "Export failed");
    }
  };

  return (
    <div className="flex items-center gap-1.5">
      {filters && (
        <Popover>
          <PopoverTrigger asChild>
            <Button size="sm" variant="outline" className="relative">
              <Filter className="w-3.5 h-3.5 mr-1.5" />
              Filter
              {activeFilterCount > 0 && (
                <span className="ml-1.5 inline-flex h-4 min-w-4 items-center justify-center rounded-full bg-primary px-1 text-[10px] font-bold text-primary-foreground">
                  {activeFilterCount}
                </span>
              )}
            </Button>
          </PopoverTrigger>
          <PopoverContent className="w-72" align="end">
            <div className="space-y-3">
              <p className="font-display text-sm font-semibold">Export filters</p>
              {filters.dateField && (
                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <Label className="text-[11px]">From</Label>
                    <Input type="date" value={from} onChange={(e) => setFrom(e.target.value)} className="h-8 text-xs" />
                  </div>
                  <div>
                    <Label className="text-[11px]">To</Label>
                    <Input type="date" value={to} onChange={(e) => setTo(e.target.value)} className="h-8 text-xs" />
                  </div>
                </div>
              )}
              {filters.statusField && filters.statusOptions && (
                <div>
                  <Label className="text-[11px]">Status</Label>
                  <div className="mt-1 flex flex-wrap gap-1">
                    <button
                      onClick={() => setStatus("all")}
                      className={`rounded-full border px-2 py-0.5 text-[11px] transition-colors ${status === "all" ? "border-primary bg-primary/15 text-primary" : "border-border/40 text-muted-foreground hover:text-foreground"}`}
                    >
                      All
                    </button>
                    {filters.statusOptions.map((opt) => (
                      <button
                        key={opt}
                        onClick={() => setStatus(opt)}
                        className={`rounded-full border px-2 py-0.5 text-[11px] transition-colors ${status === opt ? "border-primary bg-primary/15 text-primary" : "border-border/40 text-muted-foreground hover:text-foreground"}`}
                      >
                        {opt}
                      </button>
                    ))}
                  </div>
                </div>
              )}
              {filters.clientField && (
                <div>
                  <Label className="text-[11px]">Client contains</Label>
                  <Input value={client} onChange={(e) => setClient(e.target.value)} placeholder="Search…" className="h-8 text-xs" />
                </div>
              )}
              {activeFilterCount > 0 && (
                <Button size="sm" variant="ghost" className="w-full text-xs" onClick={() => { setFrom(""); setTo(""); setStatus("all"); setClient(""); }}>
                  Reset filters
                </Button>
              )}
              <p className="text-[10px] text-muted-foreground">{filtered.length} of {rows.length} rows match</p>
            </div>
          </PopoverContent>
        </Popover>
      )}
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button size="sm" variant="outline">
            <Download className="w-3.5 h-3.5 mr-1.5" /> Export
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent align="end" className="w-48">
          <DropdownMenuLabel className="text-[10px] uppercase tracking-wide text-muted-foreground">
            {filtered.length} rows {activeFilterCount > 0 ? "(filtered)" : ""}
          </DropdownMenuLabel>
          <DropdownMenuSeparator />
          <DropdownMenuItem onClick={handleCSV}>
            <FileSpreadsheet className="w-3.5 h-3.5 mr-2" /> Download CSV
          </DropdownMenuItem>
          <DropdownMenuItem onClick={handlePDF}>
            <FileText className="w-3.5 h-3.5 mr-2" /> Download PDF
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>
    </div>
  );
}
