// Reusable CSV/PDF export dropdown for finance & ops pages.
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Download, FileText, FileSpreadsheet } from "lucide-react";
import { downloadCSV, downloadPDF } from "@/lib/exporters";
import { toast } from "sonner";

interface ExportMenuProps {
  filename: string;
  title: string;
  rows: Record<string, any>[];
  headers?: string[];
  subtitle?: string;
}

export function ExportMenu({ filename, title, rows, headers, subtitle }: ExportMenuProps) {
  const handleCSV = () => {
    try {
      downloadCSV(`${filename}.csv`, rows, headers);
      toast.success("CSV exported");
    } catch (e: any) {
      toast.error(e.message || "Export failed");
    }
  };

  const handlePDF = async () => {
    try {
      await downloadPDF(`${filename}.pdf`, title, rows, headers, { subtitle, footer: "Generated by Digital Penta · digitalpenta.com" });
      toast.success("PDF exported");
    } catch (e: any) {
      toast.error(e.message || "Export failed");
    }
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button size="sm" variant="outline">
          <Download className="w-3.5 h-3.5 mr-1.5" /> Export
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end" className="w-44">
        <DropdownMenuItem onClick={handleCSV}>
          <FileSpreadsheet className="w-3.5 h-3.5 mr-2" /> Download CSV
        </DropdownMenuItem>
        <DropdownMenuItem onClick={handlePDF}>
          <FileText className="w-3.5 h-3.5 mr-2" /> Download PDF
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
}
