// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygoxxqkcxunuowtuwdxr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlnb3h4cWtjeHVudW93dHV3ZHhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1Mjk3NTAsImV4cCI6MjA3MTEwNTc1MH0.95NbFoK8HXaMzA1E0V9a1hpqSs_VQJRI4Z9ImqNQJ9I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});